# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details

version: 2
jobs:
  build-web:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: explorer-web-{{ .Branch }}-{{ checksum "web-ui/package-lock.json" }}
      - run: cd web-ui && npm install
      - save_cache:
          key: explorer-web-{{ .Branch }}-{{ checksum "web-ui/package-lock.json" }}
          paths:
            - "web-ui/node_modules"
      - run: cd web-ui && npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      # - run: cd web-ui && npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

workflows:
  version: 2
  build:
    jobs:
      - build-web

